### ISSUE TITLE
[CRITICAL BUG] Losing blocks

### ISSUE THREAD

**Issue by UnioDex** [connection-lost/LockettePro#32]
**Version Information:**
LockettePro: 2.6.4
Spigot: 1.8

**Bug Information:**
A player sent me a bug report about losing spawners. When you try to put a spawner on locked spawner your spawner is losing and block not being placed.  Than i make a video to reproduce. Also is it a bug not to put another block on the blocks?

**Video:**
https://youtu.be/ov5swAc6wVs

**Comment by connection-lost** [comment]
Which custom spawner plugin are you using?

**Comment by UnioDex** [comment]
I have a custom private plugin.

**Comment by connection-lost** [comment]
Please send me privately at frankwu1995(at)hotmail.com

I solved a similar issue a year ago. It is possible that your custom plugin has a little incompatibility and requires a one line rewrite.

**Comment by UnioDex** [comment]
I sent.

**Comment by connection-lost** [comment]
I have 2 recommended solution for you:

1. (Good solution)
At Main.java, line 287:
Please change this line
    @EventHandler
to
    @EventHandler(priority=EventPriority.Highest)

2. (Fair solution)
At Main.java, line 288, for the entire method "BlokKoyunca(BlockPlaceEvent event)":
Please use "event.setCancelled()" if the spawner is correctly placed.

**Comment by UnioDex** [comment]
I did but problem still continues.

**Comment by UnioDex** [comment]
Oh block disappearing problem is solved but still cant put a block on a spawner.

**Comment by connection-lost** [comment]
"Oh block disappearing problem is solved but still cant put a block on a spawner."
This should only happen if the you do not have permission to the other spawner... Please try confirm, I will look into it again if it is not the case.

**Comment by UnioDex** [comment]
Yes, no permission to the other block. But why players cant put a spawner on a another persons spawner?

**Comment by connection-lost** [comment]
I'll go check again

**Comment by connection-lost** [comment]
"Yes, no permission to the other block. But why players cant put a spawner on a another persons spawner?"

Wait nonono, sorry for my previous reply, but this is intended! You are not supposed to "interact" with people's block, even you cannot interact with them. This is because locking a chest/furnace/anvil should prevent unauthorized players from interacting with them. Locking a stone is not necessary to prevent interaction, but preventing interaction will avoid conflict with other plugins. In this case, preventing interaction with a stone will sufficiently block "super breaker pickaxe" from mcmmo.

Solution is simple: try to put the block from another direction.
