### ISSUE TITLE
Players with 16 characters nickname can't use their chests

### ISSUE THREAD

**Issue by Alexre** [connection-lost/LockettePro#64]
I have been using the normal lockette, after upgrading to lockettepro, players with 16 characters nickname length can't use their chests.

**Comment by connection-lost** [comment]
It was Lockette's fault for not storing the correct name on signs. If I remember correctly, Lockette will trim all player's name to 15 characters due to Minecraft 1.8 and below can only have 15 characters on each line of a sign. The player names should not be trimmed above 1.8, and LockettePro is designed for servers 1.8+ only.

Even I want to fix this issue, there is nothing can be done. If I only check first 15 letters of each line, malicious player will change its name that only match the first 15 characters and open the chest that does not belong to him.
